apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: core.platform-mesh.io
spec:
  permissionClaims:
  - resource: namespaces
    verbs: null
  - group: tenancy.kcp.io
    identityHash: '{{ .data.apiExportRootTenancyKcpIoIdentityHash }}'
    resource: workspaces
    verbs: null
  - group: tenancy.kcp.io
    identityHash: '{{ .data.apiExportRootTenancyKcpIoIdentityHash }}'
    resource: workspacetypes
    verbs: null
  resources:
  - group: core.platform-mesh.io
    name: accountinfos
    schema: v260126-7c674ee.accountinfos.core.platform-mesh.io
    storage:
      crd: {}
  - group: core.platform-mesh.io
    name: accounts
    schema: v260109-82344be.accounts.core.platform-mesh.io
    storage:
      crd: {}
status: {}
